# Generated by Django 5.2.12 on 2026-05-22 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "rut",
                    models.CharField(blank=True, max_length=20, verbose_name="RUT"),
                ),
                ("contacto", models.CharField(blank=True, max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Sucursales",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=50, unique=True)),
                (
                    "unidad_medida",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogramo"),
                            ("lt", "Litro"),
                            ("un", "Unidad"),
                            ("cj", "Caja"),
                            ("bz", "Bolsa"),
                            ("pqt", "Paquete"),
                        ],
                        default="un",
                        max_length=10,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="api.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarritoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.carrito",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.producto"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de aprobación"),
                            ("aprobado", "Aprobado por logística"),
                            ("preparacion", "En preparación"),
                            ("enviado", "Enviado al local"),
                            ("recibido", "Recibido en el local"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado_por", models.CharField(blank=True, max_length=200)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "carrito",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.carrito",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="api.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Merma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "razon",
                    models.CharField(
                        choices=[
                            ("caducidad", "Caducidad"),
                            ("mal_estado", "Mal estado"),
                            ("error_cocina", "Error de cocina"),
                            ("rotura", "Rotura/derrame"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("responsable", models.CharField(max_length=200)),
                ("fecha", models.DateField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.producto"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mermas",
                        to="api.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mermas",
            },
        ),
        migrations.AddField(
            model_name="carrito",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carritos",
                to="api.sucursal",
            ),
        ),
        migrations.CreateModel(
            name="AlertaStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("critico", "Crítico — stock agotado"),
                            ("bajo", "Bajo — por debajo del mínimo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("stock_actual", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_minimo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("leida", models.BooleanField(default=False)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.producto"
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="api.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductoProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("activo", models.BooleanField(default=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios_proveedor",
                        to="api.producto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="api.proveedor",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precios_proveedor",
                        to="api.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Productos por Proveedor",
                "unique_together": {("producto", "proveedor", "sucursal")},
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lote", models.CharField(blank=True, max_length=100)),
                (
                    "stock_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_recepcion", models.DateField(blank=True, null=True)),
                ("fecha_caducidad", models.DateField(blank=True, null=True)),
                (
                    "ubicacion",
                    models.CharField(
                        choices=[
                            ("superior", "Nivel Superior — listos para consumo"),
                            ("medio", "Nivel Medio — frutas/verduras"),
                            ("inferior", "Nivel Inferior — carnes crudas"),
                            ("secos", "Zona de Secos"),
                        ],
                        default="secos",
                        max_length=50,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="api.producto",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario",
                        to="api.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventario",
                "unique_together": {("sucursal", "producto", "lote")},
            },
        ),
    ]
