# Generated by Django 5.2.12 on 2026-05-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_caja_producto_precio_venta_cajaproducto_movimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="control_calidad_ok",
            field=models.BooleanField(
                blank=True,
                help_text="False si el producto fue rechazado por control de calidad",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="inspeccion_visual",
            field=models.TextField(
                blank=True,
                help_text="Resultado de inspeccion organoleptica (color, olor, textura, envases)",
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="rechazo_motivo",
            field=models.CharField(
                blank=True, help_text="Motivo de rechazo si aplica", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="temp_ok",
            field=models.BooleanField(
                blank=True,
                help_text="True si temp entre 0-5°C (refrig) o <= -18°C (congelado)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movimiento",
            name="temperatura",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Temperatura del producto al recibir (Celsius)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimiento",
            name="metodo",
            field=models.CharField(
                choices=[("manual", "Manual"), ("camara", "Camara / QR")],
                default="manual",
                max_length=10,
            ),
        ),
    ]
