# Generated by Django 5.2.12 on 2026-05-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_movimiento_control_calidad_ok_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="orden_compra_numero",
            field=models.CharField(
                blank=True,
                help_text="Numero de Orden de Compra asociada (verificacion documental)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tipo_conservacion",
            field=models.CharField(
                choices=[
                    ("refrigerado", "Refrigerado (0°C a 5°C)"),
                    ("congelado", "Congelado (<= -18°C)"),
                    ("seco", "Seco / Ambiente"),
                ],
                default="seco",
                help_text="Define los rangos de temperatura aceptados en recepcion",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("rechazo", "Rechazo en recepcion"),
                            ("alerta", "Alerta de stock"),
                            ("pedido", "Nuevo pedido"),
                            ("sistema", "Mensaje del sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                (
                    "referencia_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del movimiento/pedido relacionado",
                        null=True,
                    ),
                ),
                ("leida", models.BooleanField(default=False)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="api.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-creada_en"],
            },
        ),
    ]
