# Generated by Django 5.2.12 on 2026-05-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_movimiento_orden_compra_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="aprobado_por",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pedido",
            name="rechazado_motivo",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="SugerenciaPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_sugerida",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("stock_actual", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_minimo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("ignorada", "Ignorada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.producto"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.proveedor",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sugerencias",
                        to="api.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sugerencias de Pedido",
                "ordering": ["-creada_en"],
            },
        ),
    ]
