# Generated by Django 5.2.12 on 2026-05-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_pedido_aprobado_por_pedido_rechazado_motivo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conteo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responsable", models.CharField(max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_progreso", "En progreso"),
                            ("completado", "Completado"),
                        ],
                        default="en_progreso",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("completado_en", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteos",
                        to="api.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Conteos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ConteoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_sistema",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cantidad_fisica",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("ajustado", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "conteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="api.conteo",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.producto"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Productos de Conteo",
                "unique_together": {("conteo", "producto")},
            },
        ),
    ]
