# Generated by Django 5.2.12 on 2026-05-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_conteo_conteoproducto"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(max_length=500)),
                ("auth", models.CharField(max_length=100)),
                ("p256dh", models.CharField(max_length=200)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
