# Generated by Django 5.2.12 on 2026-05-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="merma",
            name="perdida",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Perdida calculada = cantidad * precio_venta del producto",
                max_digits=12,
            ),
        ),
    ]
